### ISSUE TITLE
io.minio.nifi.MinIORepository Failed to cleanup content claims due to {}

### ISSUE THREAD

**Issue by harshavardhana** [minio/nifi-minio#1]
2019-07-31 18:14:07,172 ERROR [MinIORepository Workers Thread-1] io.minio.nifi.MinIORepository Failed to cleanup content claims due to {}
java.lang.NullPointerException: null
        at io.minio.nifi.MinIORepository$BinDestructableClaims.run(MinIORepository.java:912)
        at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by harshavardhana** [comment]
Fixed in master closing.
